#!/bin/sh
echo "--> removing hosts from rancher"
rancher deactivate $(rancher hosts -q)
rancher rm $(rancher hosts -a -q)

echo "--> Stopping rancher-server if running"
docker stop rancher-server

echo "--> running make_snapshot"
./devops/make_snapshot.sh

echo " --> adding new snapshot(s) to commit"
git add snapshots/**.7z
