version: '3'
services:

# Development (Mac OS X)
################################################################################
  proxy:
    build: ./development/docker-mac-network
    ports:
      - "127.0.0.1:13194:13194"
    command: TCP-LISTEN:13194,fork TCP:172.17.0.1:1194

  openvpn:
    image: kylemanna/openvpn
    volumes:
      - ./development/docker-mac-network:/local
      - ./development/docker-mac-network/config:/etc/openvpn
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      dest: docker-for-mac.ovpn
    command: /local/helpers/run.sh

# DevOps
################################################################################

  # Postgres our Database.
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ""
    volumes:
    - ./storage/postgres:/var/lib/postgresql/data

################################################################################

  # API Gateway (TODO: Basic Image for Services.)
  gateway:
    build: ./services/gateway
    ports: ["80"] # Docker for Mac fix for no ports.
    volumes:
      - ./services/gateway:/gateway
      - ./services/libcommunication/js:/gateway/node_modules/libcommunication

  users:
    build: ./services/users
    volumes:
      - ./services/users:/users
      - ./services/libcommunication/js:/users/node_modules/libcommunication
