#!/usr/bin/env bash
# (c) 2016 StayMarta
#
# Create a worker and add it to Rancher.
#
# create-worker [OPTION]
#
#   -d       Dry run (doesn\'t create the worker.)

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

WORKERS_DIR="${DIR}/../storage"
SCRIPTS_DIR="${DIR}/../.setup"

# Load our config.
. ${SCRIPTS_DIR}/config.sh

# Check if any machine actually exist.
if [[ ! -e "${WORKERS_DIR}" ]]; then
  ERROR "No workers directory."
  exit 10
fi

WORKER_COUNT=0
for file in $(ls ${WORKERS_DIR}); do
  WORKER_COUNT=$((WORKER_COUNT+1))
done

INFO "Found ${WORKER_COUNT} workers."
NEW_WORKER=$((WORKER_COUNT+1))

INFO "Creating worker ${NEW_WORKER}"

if [[ "$1" == "-d" ]]; then
  WARN "Dry run. Exiting."
  exit
fi

${SCRIPTS_DIR}/create-worker.sh ${NEW_WORKER}
