#!/usr/bin/env bash
#
# (c) 2017 StayMarta
#
# Upgrade the rancher installation.
#
# upgrade [OPTIONS]
#
#   -d      Dry run

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

WORKERS_DIR="${DIR}/../storage"
SCRIPTS_DIR="${DIR}/../.setup"

# Load our config.
. ${SCRIPTS_DIR}/config.sh

docker pull ${SERVER_DOCKER_IMAGE}

################################################################################
# Remove the old container

CONTAINER_ID="$(docker ps | grep "${SERVER_DOCKER_IMAGE}" | awk '{ print $1 }')"
INFO "Deleting existing container: ${CONTAINER_ID}"

if [[ "$1" != "-d" ]]; then
  SUB "Stopping container."
  docker stop ${CONTAINER_ID}

  SUB "removing container"
  docker rm ${CONTAINER_ID}
else
  WARN "dry-run, not deleting."
fi

################################################################################
# Create a new container.

INFO "Creating new container"
if [[ "$1" == "-d" ]]; then
  WARN "dry-run, exiting."
  exit
fi

docker run --name rancher-server -d -v "${DIR}/../rancher/mysql:/var/lib/mysql" -p 8080:8080 ${SERVER_DOCKER_IMAGE}

INFO "Done! ☕️"
